parameters:  
  serviceConnection: 'AzureDevopsCon1'
  resourceGroupName: 'tfstaterg'
  location: 'westeurope'
  storageAccountName: 'tfstatecontainer20241119'
  containerName: 'tfstate-container'
  storageKey: 'terraform.tfstate'
  varFile: 'dev-variables.tfvars'
  storageSKU: 'Standard_LRS'
  environmentServiceNameAzureRM: ''
  backendServiceArm: 'AzureDevopsCon1'
  backendAzureRmResourceGroupName: 'rgtest1'
  backendAzureRmStorageAccountName: 'strgtestdevopagent1'
  backendAzureRmContainerName: 'terraform01'
  backendAzureRmKey: 'terraform.tfstate'